_name_: hyena
l_max: 1024
order: 2
filter_order: 64
num_heads: 1
inner_factor: 1
num_blocks: 1
fused_bias_fc: false
outer_mixing: false
dropout: 0.0 
filter_dropout: 0.0
filter_cls: 'hyena-filter'
post_order_ffn: false
jit_filter: false
short_filter_order: 3
activation: "id"